sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.main:
                label:  Admin
                label_catalogue: AppBundle
                icon: '<i class="fa fa-database"></i>'
                items:
                    - app.admin.product
                    - app.admin.category
                    - app.admin.client

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
