sonata_admin:
    title: 'jkuweb'
    title_logo: '/bundles/sonataadmin/images/logo.jpeg'
    assets:
        extra_stylesheets:
            - bundles/sonataadmin/custom.css
    global_search:
       empty_boxes: hide       
  
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.main:
                label:  Admin
                label_catalogue: AppBundle
                icon: '<i class="fa fa-database"></i>'
                items:
                    - app.admin.product
                    - app.admin.category
                    - app.admin.client
                    - app.admin.order

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
