parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    app.admin.category:
        class: App\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Category, manager_type: orm, label: Categorías }

    app.admin.product:
        class: App\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Product, manager_type: orm, label: Producto }        

    app.admin.client:
        class: App\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Client, manager_type: orm, label: Cliente }        

    app.admin.address:
        class: App\Admin\AddressAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Address, manager_type: orm, label: Dirección }        
    
    app.admin.order:
        class: App\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\ClientOrder, manager_type: orm, label: Pedidos }        